name: Deployment Demo
on:
  push:
    branches: [ main, test-branch ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Deploy target server'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  setup_deployment:
    uses: ./.github/workflows/cd.yml
    with:
      deploy_target: ${{ inputs.deploy_target }}

    