name: Deployment Demo
on:
  push:
    branches: [ main, test-branch ]
  pull_request:
    branches: [ main ]

jobs:
  initial-job:
    name: "Initial job"
    runs-on: ubuntu-latest
    steps:
    - name: First step
      id: init
      run: |
        echo "Starting CI/CD demo for ${{ github.repository }}"

  deploy_to_development:
    name: "Development Deployment"
    if: ${{ github.ref != 'refs/heads/main' }}
    needs: initial-job
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Which dir
      run: |
        pwd
        cd .github
        ls -a
  
    # Check for production deployment by authorized user
    - name: Can actor do production deployment? 
      uses: natterstefan/action-eligible-actor@v1
      with:
        rulesFile: 'eligible-actors-rules.json' # default
        ruleId: 1 # required

    - name: Deploy to Development
      if: ${{ github.ref != 'refs/heads/main' }}
      run: |
        echo "Deploying to Development environment!"

  deploy_to_staging:
    name: "Staging Deployment"
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: initial-job
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Staging
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        echo "Deploying to Staging environment!"

  deploy_to_production:
    name: "Production Deployment"
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: initial-job
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Production
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        echo "Deploying to Production environment!"


    