name: Deployment Demo
on:
  pull_request:
    branches: [ main ]

jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: SuttonJack/jira-lint@v1.3
        name: jira-lint
        with:
          github-token: ${{ secrets.TOKEN_GA }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://kfit-asia.atlassian.net
          jira-user: syahmi.ahmad@myfave.com
          skip-comments: true
          pr-threshold: 1000
