name: TEST
run-name: "Just testing"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
on:
  push:
    branches: [ main, test-branch ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Deploy target server'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  cd_deploy:
    uses: ./.github/workflows/cd.yml
    with:
      deploy_target: ${{ inputs.deploy_target }}
    secrets: inherit

    
