name: Deployment Demo
on:
  pull_request:
    branches: [ main ]

jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: jira-tools/action-jira-linter@v1.0.1
        name: jira-lint
        with:
          github-token: ${{ secrets.TOKEN_GA }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://kfit-asia.atlassian.net
          skip-comments: true
          pr-threshold: 1000
